"""empty message

Revision ID: 7c968eef5658
Revises: 556f4be52b8f
Create Date: 2021-02-13 11:44:10.192442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c968eef5658'
down_revision = '556f4be52b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column(
        'completed', sa.Boolean(), nullable=True))


op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

op.alter_column('todos', 'completed', nullable=False)


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
